### ISSUE TITLE
Set up a CI environment

### ISSUE THREAD

**Issue by avdata99** [datopian/ckan-ng-harvester-core#1]
Since we are moved from GitLab to GitHub we will need a CI environment

### Tasks

* [ ] Check the tasks at _.gitlab-ci.yml_
* [ ] Define a new environment
* [ ] Apply and test

**Comment by thejuliekramer** [comment]
I added a simple github script to run the tests that don't require ckan for now at .github/workflows/test_script.yml this also runs flake8 on the codebase

**Comment by woodt** [comment]
(I'm adding myself to this, since we lost the security scanning steps from the old pipeline in the move to GitHub.)

**Comment by avdata99** [comment]
Added to Travis (including bandit @woodt): https://github.com/datopian/ckan-ng-harvester-core/blob/master/.travis.yml
Is passing: https://travis-ci.org/datopian/ckan-ng-harvester-core
Deploy to Pypi is working: https://pypi.org/project/ckan-harvesters/

If you validate this Travis set up @akariv, please close this
